// Census import: datenanfragen.de community database → generated TS snapshot.
//
// Source: github.com/datenanfragen/data — CC0-1.0 (public-domain dedication, verified in LICENSE).
// The records are community-curated and carry a `quality` tier + `sources`; we retain both. This is
// IMPORT, NOT ACTIVATION (docs/10 §3 P0): the snapshot enriches the alpha census with sourced
// contact channels; it never overrides hand-curated fields, never activates a playbook, and every
// channel is re-verified by counsel before a real send (docs/07).
//
// Run:  node tools/census-import/import.mjs        (writes apps/api/src/census/datenanfragen.snapshot.ts)
//
// Community data is untrusted input: only known scalar fields are copied, strings are length-capped,
// and the output is a generated literal — no code from the network is ever evaluated.

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const RAW = 'https://raw.githubusercontent.com/datenanfragen/data/master/companies';

// our census slug → datenanfragen slug (their naming differs; obsolete records redirect upstream).
const SLUG_MAP = {
  schufa: 'schufa',
  infoscore: 'infoscore',
  crif: 'crifbuergel',
  regis24: 'regis24',
  'az-direct': 'az-direct',
  acxiom: 'acxiom',
  'deutsche-post-direkt': 'deutsche-post-direkt',
  capaneo: 'schober', // Schober → Capaneo merger; their live record keeps the schober slug
  zoominfo: 'zoominfo',
  apollo: 'apollo-io',
  lusha: 'lusha',
  cognism: 'cognism',
  peopledatalabs: 'people-data-labs',
  rocketreach: 'rocketreach',
  hirevue: 'hirevue', // may not exist — recorded as missing, not an error
};

const cap = (s, n = 500) => (typeof s === 'string' ? s.slice(0, n) : undefined);

function transform(ours, theirs, json) {
  return {
    sourceSlug: theirs,
    name: cap(json.name, 120),
    address: cap(json.address, 300),
    email: cap(json.email, 200),
    fax: cap(json.fax, 60),
    web: cap(json.web, 200),
    suggestedTransport: cap(json['suggested-transport-medium'], 20),
    needsIdDocument: json['needs-id-document'] === true,
    requiredElements: Array.isArray(json['required-elements'])
      ? json['required-elements'].map((e) => cap(e?.type, 40)).filter(Boolean).slice(0, 10)
      : [],
    quality: cap(json.quality, 20),
    sources: Array.isArray(json.sources) ? json.sources.map((s) => cap(s, 300)).filter(Boolean).slice(0, 6) : [],
  };
}

const records = {};
const missing = [];
for (const [ours, theirs] of Object.entries(SLUG_MAP)) {
  const res = await fetch(`${RAW}/${theirs}.json`);
  if (!res.ok) {
    missing.push(`${ours} (tried ${theirs}: HTTP ${res.status})`);
    continue;
  }
  records[ours] = transform(ours, theirs, await res.json());
  console.log(`  ✓ ${ours} ← ${theirs} (quality: ${records[ours].quality})`);
}

const out = `// GENERATED by tools/census-import/import.mjs — DO NOT EDIT BY HAND.
// Data: github.com/datenanfragen/data (CC0-1.0). Community-curated; per-record quality + sources
// retained. Enrichment only — hand-curated census fields always win; counsel re-verifies channels
// before any real send (docs/07). Regenerate: node tools/census-import/import.mjs

export interface DatenanfragenRecord {
  readonly sourceSlug: string;
  readonly name?: string;
  readonly address?: string;
  readonly email?: string;
  readonly fax?: string;
  readonly web?: string;
  readonly suggestedTransport?: string;
  readonly needsIdDocument: boolean;
  readonly requiredElements: readonly string[];
  readonly quality?: string;
  readonly sources: readonly string[];
}

export const DATENANFRAGEN_SNAPSHOT: {
  readonly retrievedAt: string;
  readonly license: 'CC0-1.0';
  readonly missing: readonly string[];
  readonly records: Readonly<Record<string, DatenanfragenRecord>>;
} = ${JSON.stringify({ retrievedAt: new Date().toISOString(), license: 'CC0-1.0', missing, records }, null, 2)};
`;

const dest = join(dirname(fileURLToPath(import.meta.url)), '../../apps/api/src/census/datenanfragen.snapshot.ts');
await writeFile(dest, out, 'utf8');
console.log(`\nwrote ${dest}`);
if (missing.length) console.log(`missing (ok, recorded): ${missing.join('; ')}`);
