// GENERATED by tools/census-import/import.mjs — DO NOT EDIT BY HAND.
// Data: github.com/datenanfragen/data (CC0-1.0). Community-curated; per-record quality + sources
// retained. Enrichment only — hand-curated census fields always win; counsel re-verifies channels
// before any real send (docs/07). Regenerate: node tools/census-import/import.mjs

export interface DatenanfragenRecord {
  readonly sourceSlug: string;
  readonly name?: string;
  readonly address?: string;
  readonly email?: string;
  readonly fax?: string;
  readonly web?: string;
  readonly suggestedTransport?: string;
  readonly needsIdDocument: boolean;
  readonly requiredElements: readonly string[];
  readonly quality?: string;
  readonly sources: readonly string[];
}

export const DATENANFRAGEN_SNAPSHOT: {
  readonly retrievedAt: string;
  readonly license: 'CC0-1.0';
  readonly missing: readonly string[];
  readonly records: Readonly<Record<string, DatenanfragenRecord>>;
} = {
  "retrievedAt": "2026-08-11T02:49:21.702Z",
  "license": "CC0-1.0",
  "missing": [
    "cognism (tried cognism: HTTP 404)",
    "peopledatalabs (tried people-data-labs: HTTP 404)",
    "hirevue (tried hirevue: HTTP 404)"
  ],
  "records": {
    "schufa": {
      "sourceSlug": "schufa",
      "name": "SCHUFA Holding AG",
      "address": "Kormoranweg 5\n65201 Wiesbaden\nDeutschland",
      "email": "datenschutz@schufa.de",
      "fax": "+49 611 9278109",
      "web": "https://www.schufa.de",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address"
      ],
      "quality": "verified",
      "sources": [
        "https://www.schufa.de/de/datenschutz/",
        "https://www.schufa.de/de/impressum/",
        "https://github.com/datenanfragen/data/pull/3031"
      ]
    },
    "infoscore": {
      "sourceSlug": "infoscore",
      "name": "infoscore Consumer Data GmbH",
      "address": "Rheinstraße 99\n76532 Baden-Baden\nDeutschland",
      "email": "ICD-Datenschutz@experian.com",
      "web": "https://www.experian.de/",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address",
        "birthdate",
        "address"
      ],
      "quality": "verified",
      "sources": [
        "https://www.experian.de/selbstauskunft",
        "https://www.experian.de/icd-artikel-13",
        "https://www.northdata.de/?id=4887812606001152",
        "https://github.com/datenanfragen/data/issues/100",
        "https://github.com/datenanfragen/data/issues/637",
        "https://github.com/datenanfragen/data/pull/2201"
      ]
    },
    "crif": {
      "sourceSlug": "crifbuergel",
      "name": "CRIF GmbH",
      "address": "Leopoldstraße 244\n80807 München\nDeutschland",
      "email": "datenschutz.de@crif.com",
      "fax": "+49 40 89803309",
      "web": "https://www.crif.de",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address"
      ],
      "quality": "verified",
      "sources": [
        "https://www.crif.de/konsumenten/selbstauskunft/",
        "https://www.crif.de/datenschutz",
        "https://www.crif.com/news-events/press/deltavista-gmbh-renamed-crif-gmbh/",
        "https://github.com/datenanfragen/data/issues/636",
        "https://github.com/datenanfragen/data/pull/3815"
      ]
    },
    "regis24": {
      "sourceSlug": "regis24",
      "name": "Regis24 GmbH",
      "address": "Alte Rhinstr. 16\n12681 Berlin\nDeutschland",
      "email": "datenschutz@regis24.de",
      "fax": "+49 30 44350249",
      "web": "https://www.regis24.de",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address",
        "birthdate"
      ],
      "quality": "tested",
      "sources": [
        "https://www.regis24.de/datenschutz/",
        "https://www.regis24.de/impressum/",
        "https://github.com/datenanfragen/data/pull/699",
        "https://be.m.mail.regis24.de/asset/33:antragsformular-selbstauskunft-regis24pdf"
      ]
    },
    "az-direct": {
      "sourceSlug": "az-direct",
      "name": "AZ Direct GmbH",
      "address": "Carl-Bertelsmann-Straße 161S\n33311 Gütersloh\nDeutschland",
      "email": "datenschutz@az-direct.com",
      "fax": "+49 5241 8066909",
      "web": "https://www.az-direct.com",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address",
        "address"
      ],
      "quality": "tested",
      "sources": [
        "https://www.az-direct.com/site/dm",
        "https://github.com/datenanfragen/data/pull/1179"
      ]
    },
    "acxiom": {
      "sourceSlug": "acxiom",
      "name": "Acxiom Deutschland GmbH",
      "address": "Speicherstraße 57-59\n60327 Frankfurt am Main\nDeutschland",
      "email": "datenschutz@acxiom.com",
      "web": "http://www.acxiom.de/",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address"
      ],
      "quality": "verified",
      "sources": [
        "https://www.acxiom.de/datenschutz/datenschutzinformationen-fuer-verbraucher-und-firmendatenbank/",
        "https://www.acxiom.de/impressum/",
        "https://github.com/datenanfragen/data/pull/1099",
        "https://github.com/datenanfragen/data/pull/2346"
      ]
    },
    "deutsche-post-direkt": {
      "sourceSlug": "deutsche-post-direkt",
      "name": "Deutsche Post Direkt GmbH",
      "address": "Junkersring 57\n53844 Troisdorf\nDeutschland",
      "email": "datenschutz@postdirekt.de",
      "fax": "+49 69 65301500072",
      "web": "https://service.postdirekt.de/portal/",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [
        "name",
        "address"
      ],
      "quality": "verified",
      "sources": [
        "https://service.postdirekt.de/portal/datenschutz",
        "https://service.postdirekt.de/portal/impressum",
        "https://github.com/datenanfragen/data/pull/3813"
      ]
    },
    "capaneo": {
      "sourceSlug": "schober",
      "name": "Capaneo GmbH",
      "address": "Meisenweg 37\n70771 Leinfelden-Echterdingen\nDeutschland",
      "email": "datenschutz@capaneo.de",
      "fax": "+49 711 953584369",
      "web": "https://capaneo.de",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [],
      "quality": "verified",
      "sources": [
        "https://capaneo.de/datenschutz/",
        "https://capaneo.de/news/aus-schober-wird-capaneo/",
        "https://github.com/datenanfragen/data/pull/775",
        "https://github.com/datenanfragen/data/pull/3824"
      ]
    },
    "zoominfo": {
      "sourceSlug": "zoominfo",
      "name": "Zoom Information, Inc.",
      "address": "330 W Columbia Way\nFloor 8, Vancouver\nWA 98660\nUnited States of America",
      "email": "privacy@zoominfo.com",
      "web": "https://zoominfo.com",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [],
      "quality": "verified",
      "sources": [
        "https://www.zoominfo.com/about-zoominfo/privacy-policy",
        "https://github.com/datenanfragen/data/pull/1716",
        "https://github.com/datenanfragen/data/pull/3459"
      ]
    },
    "apollo": {
      "sourceSlug": "apollo-io",
      "name": "Apollo.io",
      "address": "440 N Barranca Ave #4750\nCovina\nCA 91723-1722\nUnited States of America",
      "email": "privacy@apollo.io",
      "web": "https://apollo.io",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [],
      "quality": "verified",
      "sources": [
        "https://www.apollo.io/privacy-policy",
        "https://techcrunch.com/2018/06/26/yc-grad-zenprospect-rebrands-as-apollo-lands-7-m-series-a/",
        "https://github.com/datenanfragen/data/issues/582"
      ]
    },
    "lusha": {
      "sourceSlug": "lusha",
      "name": "Lusha Systems Inc.",
      "address": "1177 Avenue of the Americas\n5th Floor\nNew York NY 10036\nUnited States of America",
      "email": "Privacy@Lusha.com",
      "web": "https://www.lusha.co/",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [],
      "quality": "verified",
      "sources": [
        "https://github.com/datenanfragen/data/issues/115",
        "https://github.com/datenanfragen/data/issues/114",
        "https://www.lusha.co/gdpr/",
        "https://www.lusha.co/privacy_policy/",
        "https://www.lusha.com/legal/terms_and_conditions/"
      ]
    },
    "rocketreach": {
      "sourceSlug": "rocketreach",
      "name": "RocketReach",
      "address": "144 N 7th St\nPO #421\nBrooklyn, NY 11211\nUnited States of America",
      "email": "article27@verasafe.com",
      "web": "https://rocketreach.co",
      "suggestedTransport": "email",
      "needsIdDocument": false,
      "requiredElements": [],
      "quality": "verified",
      "sources": [
        "https://rocketreach.co/privacy",
        "https://github.com/datenanfragen/data/issues/493",
        "https://github.com/datenanfragen/data/pull/2835"
      ]
    }
  }
};
